version: '3'
services:
  node:
    tty: true
    stdin_open: true
    container_name: express-proxy-server
    build:
      context: .
    volumes:
      - .:/var/code:rw
    entrypoint: './startup.sh'
